// Code generated by gotmpl. DO NOT MODIFY.
// source: internal/shared/semconv/util_test.go.tmpl

// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package semconv

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/otel/attribute"
	semconvNew "go.opentelemetry.io/otel/semconv/v1.34.0"
)

func TestSplitHostPort(t *testing.T) {
	tests := []struct {
		hostport string
		host     string
		port     int
	}{
		{"", "", -1},
		{":8080", "", 8080},
		{"127.0.0.1", "127.0.0.1", -1},
		{"www.example.com", "www.example.com", -1},
		{"127.0.0.1%25en0", "127.0.0.1%25en0", -1},
		{"[]", "", -1}, // Ensure this doesn't panic.
		{"[fe80::1", "", -1},
		{"[fe80::1]", "fe80::1", -1},
		{"[fe80::1%25en0]", "fe80::1%25en0", -1},
		{"[fe80::1]:8080", "fe80::1", 8080},
		{"[fe80::1]::", "", -1}, // Too many colons.
		{"127.0.0.1:", "127.0.0.1", -1},
		{"127.0.0.1:port", "127.0.0.1", -1},
		{"127.0.0.1:8080", "127.0.0.1", 8080},
		{"www.example.com:8080", "www.example.com", 8080},
		{"127.0.0.1%25en0:8080", "127.0.0.1%25en0", 8080},
	}

	for _, test := range tests {
		h, p := SplitHostPort(test.hostport)
		assert.Equal(t, test.host, h, test.hostport)
		assert.Equal(t, test.port, p, test.hostport)
	}
}

func TestStandardizeHTTPMethod(t *testing.T) {
	tests := []struct {
		method string
		want   attribute.KeyValue
	}{
		{"GET", semconvNew.HTTPRequestMethodKey.String("GET")},
		{"get", semconvNew.HTTPRequestMethodKey.String("GET")},
		{"POST", semconvNew.HTTPRequestMethodKey.String("POST")},
		{"post", semconvNew.HTTPRequestMethodKey.String("POST")},
		{"PUT", semconvNew.HTTPRequestMethodKey.String("PUT")},
		{"put", semconvNew.HTTPRequestMethodKey.String("PUT")},
		{"DELETE", semconvNew.HTTPRequestMethodKey.String("DELETE")},
		{"delete", semconvNew.HTTPRequestMethodKey.String("DELETE")},
		{"HEAD", semconvNew.HTTPRequestMethodKey.String("HEAD")},
		{"head", semconvNew.HTTPRequestMethodKey.String("HEAD")},
		{"OPTIONS", semconvNew.HTTPRequestMethodKey.String("OPTIONS")},
		{"options", semconvNew.HTTPRequestMethodKey.String("OPTIONS")},
		{"CONNECT", semconvNew.HTTPRequestMethodKey.String("CONNECT")},
		{"connect", semconvNew.HTTPRequestMethodKey.String("CONNECT")},
		{"TRACE", semconvNew.HTTPRequestMethodKey.String("TRACE")},
		{"trace", semconvNew.HTTPRequestMethodKey.String("TRACE")},
		{"PATCH", semconvNew.HTTPRequestMethodKey.String("PATCH")},
		{"patch", semconvNew.HTTPRequestMethodKey.String("PATCH")},
		{"unknown", semconvNew.HTTPRequestMethodKey.String("_OTHER")},
		{"", semconvNew.HTTPRequestMethodKey.String("_OTHER")},
	}
	for _, test := range tests {
		assert.Equal(t, test.want, standardizeHTTPMethod(test.method))
	}
}
